# Generated by Django 3.2.20 on 2023-08-05 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20230805_1634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='seller',
            new_name='owner',
        ),
    ]
