# Generated by Django 3.2.20 on 2023-12-22 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='car_id',
            field=models.IntegerField(default=36),
            preserve_default=False,
        ),
    ]
